services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:4000"
    volumes:
      - ./backend/src:/usr/src/app/src

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - NODE_ENV=production

volumes:
  db_data:
